# sympleq/core/symmetries/atomic_decomposition_helpers/atomic_self.py
from __future__ import annotations

import numpy as np
from typing import Any, Dict, Tuple, Optional, List

from ..modular_helpers import mod_p, independent_columns, inv_mod_mat, omega_matrix
from .atomic_types import AtomicBlock, AtomicInvariant
from .atomic_linear import (
    is_nondegenerate,
    darboux_basis_from_span,
    restrict_operator,
    symplectic_orthogonal_complement_in_span,
    mat_pow_mod,
)
from .module_invariants import jordan_chain_tops_nilpotent, cyclic_submodule_basis
from .atomic_witt import witt_decompose_form


def _cyclic_basis(F: np.ndarray, N: np.ndarray, v: np.ndarray, deg_q: int, L: int, p: int) -> np.ndarray:
    """Independent column basis for the cyclic GF(p)[x]-submodule generated by v."""
    C = cyclic_submodule_basis(F, N, v, int(deg_q), int(L), p)
    return independent_columns(mod_p(C, p), p)


def _cyclic_span_from_top_seeds(
    F: np.ndarray,
    N: np.ndarray,
    seeds: List[np.ndarray],
    deg_q: int,
    L: int,
    p: int,
) -> Optional[np.ndarray]:
    """
    Return the module span generated by one or more length-L top representatives.

    The returned basis is independent in sector coordinates.  None means that at least one
    seed failed the expected cyclic-module dimension test and should not be trusted as a
    length-L generator.
    """
    parts: List[np.ndarray] = []
    target = int(deg_q) * int(L)
    for seed in seeds:
        seed = mod_p(seed.reshape(-1, 1), p)
        if not np.any(seed % p):
            return None
        try:
            C = _cyclic_basis(F, N, seed, int(deg_q), int(L), p)
        except RuntimeError:
            return None
        if C.shape[1] != target:
            return None
        parts.append(C)
    if not parts:
        return None
    return independent_columns(np.concatenate(parts, axis=1), p)


def _extract_block_by_quotient_witt(
    F: np.ndarray,
    N: np.ndarray,
    Omega: np.ndarray,
    top_basis: np.ndarray,
    deg_q: int,
    L: int,
    p: int,
) -> Tuple[Optional[np.ndarray], Optional[str], Dict[str, Any]]:
    """
    Deterministically extract one nondegenerate cyclic/hyperbolic summand from the
    length-L top quotient using the induced quotient form.

    For representatives X of
        K_L / (K_{L-1} + N K_{L+1}),
    the induced form used here is
        b_L(x, y) = <x, N^{L-1} y>.

    We Witt-reduce this finite-dimensional quotient form over GF(p), then lift the Witt
    basis vectors to cyclic modules.  A single Witt vector may generate a whole self-dual
    cyclic module of dimension deg(q)*L; a hyperbolic pair may generate either one such
    module or a hyperbolic pair of cyclic modules, so the lifted module span is always
    verified directly against the ambient symplectic form before acceptance.
    """
    if p == 2:
        raise NotImplementedError(
            "quotient-form bilinear Witt decomposition is only valid here for odd p; "
            "p=2 self sectors need the dedicated quadratic-refinement routine."
        )

    X = independent_columns(mod_p(top_basis, p), p)
    if X.shape[1] == 0:
        return None, None, {"top_dim": 0}

    target = int(deg_q) * int(L)
    NLm1 = mat_pow_mod(N, int(L) - 1, p)
    B_top = mod_p(X.T @ Omega @ (NLm1 @ X), p)

    P, witt_blocks, witt_info = witt_decompose_form(B_top, p)
    Y = mod_p(X @ P, p)

    diagnostics: Dict[str, Any] = {
        "top_dim": int(X.shape[1]),
        "target_cyclic_dim": int(target),
        "witt": witt_info,
        "witt_blocks": [(str(t), int(i), int(j)) for (t, i, j) in witt_blocks],
        "n_single_tested": 0,
        "n_pair_tested": 0,
    }

    # First try single cyclic modules generated by the Witt basis vectors.  This catches
    # self-dual cyclic summands, including the common case where the GF(p)-top form is
    # alternating but one F_p[x]/(q)-line already lifts to a nondegenerate symplectic block.
    for idx in range(Y.shape[1]):
        diagnostics["n_single_tested"] += 1
        C = _cyclic_span_from_top_seeds(F, N, [Y[:, idx:idx + 1]], int(deg_q), int(L), p)
        if C is None or C.shape[1] != target:
            continue
        if is_nondegenerate(Omega, C, p):
            diagnostics["accepted_top_indices"] = [int(idx)]
            diagnostics["accepted_dim"] = int(C.shape[1])
            return C, "single_witt", diagnostics

    # Then try Witt hyperbolic pairs.  The cyclic closure of two top vectors can have
    # dimension target (same simple top module) or 2*target (two dual cyclic modules).  In
    # both cases we rely on the direct nondegeneracy check for certification.
    for typ, i, j in witt_blocks:
        if typ != "hyp":
            continue
        diagnostics["n_pair_tested"] += 1
        C = _cyclic_span_from_top_seeds(
            F, N,
            [Y[:, int(i):int(i) + 1], Y[:, int(j):int(j) + 1]],
            int(deg_q), int(L), p,
        )
        if C is None:
            continue
        if C.shape[1] not in (target, 2 * target):
            continue
        if is_nondegenerate(Omega, C, p):
            diagnostics["accepted_top_indices"] = [int(i), int(j)]
            diagnostics["accepted_dim"] = int(C.shape[1])
            mode = "pair_witt" if C.shape[1] == 2 * target else "single_from_hyp_witt"
            return C, mode, diagnostics

    return None, None, diagnostics



def atomic_blocks_in_self_sector_nonunipotent(
    F_sec: np.ndarray,
    T_sec: np.ndarray,
    Omega: np.ndarray,
    N: np.ndarray,
    deg_q: int,
    max_exp: int,
    p: int,
    sector_key: Tuple[int, ...],
    poly_key: Tuple[int, ...],
) -> tuple[List[AtomicBlock], AtomicInvariant]:
    """
    Certified atomic extraction for self-reciprocal, non-(x±1) sectors.

    For odd p the certified path no longer enumerates arbitrary top-space candidates.
    Instead, at each chain length L it computes the top quotient

        K_L / (K_{L-1} + N K_{L+1})

    and the induced form b_L(x,y)=<x,N^{L-1}y>, performs deterministic Witt reduction on
    that quotient form, then lifts the selected quotient vectors to full cyclic modules.

    This is the single certified route: a sector that cannot be built this way raises,
    and global completion absorbs it (reporting the result uncertified). There is no
    best-effort bounded-search fallback.
    """
    p = int(p)
    F_sec = mod_p(np.asarray(F_sec, dtype=np.int64), p)
    N = mod_p(np.asarray(N, dtype=np.int64), p)
    Omega = mod_p(np.asarray(Omega, dtype=np.int64), p)
    T_sec = mod_p(np.asarray(T_sec, dtype=np.int64), p)

    m = int(F_sec.shape[0])
    if F_sec.shape != (m, m) or N.shape != (m, m) or Omega.shape != (m, m):
        raise ValueError("shape mismatch in self-sector inputs")
    if m % 2 != 0:
        raise ValueError("self-sector dimension must be even")

    inv_data: Dict[str, Any] = {
        "status": "PENDING",
        "deg": int(deg_q),
        "exponent": int(max_exp),
        "note": "",
        "attempts": [],
        "checks_passed": [],
        "algorithm": "quotient_form_witt",
    }

    Omega_std = omega_matrix(m // 2, p)
    T_map = T_sec
    if not np.array_equal(mod_p(Omega - Omega_std, p), np.zeros_like(Omega)):
        S = darboux_basis_from_span(Omega, np.eye(m, dtype=np.int64), p)
        Sinv = inv_mod_mat(S, p)
        F = mod_p(Sinv @ F_sec @ S, p)
        Nstd = mod_p(Sinv @ N @ S, p)
        T_map = mod_p(T_sec @ S, p)
        inv_data["checks_passed"].append("darboux_normalized_sector_form")
    else:
        F = F_sec
        Nstd = N

    Omega_full = omega_matrix(m // 2, p)
    R = np.eye(m, dtype=np.int64)
    blocks: List[AtomicBlock] = []

    while R.shape[1] > 0:
        dim_r = int(R.shape[1])
        if dim_r % 2 != 0:
            msg = f"remaining dimension odd ({dim_r})"
            tail = inv_data.get("attempts", [])[-3:]
            raise RuntimeError(f"{msg}; last_attempts={tail}")

        Omega_r_target = omega_matrix(dim_r // 2, p)
        if not np.array_equal(
            mod_p(R.T @ Omega_full @ R - Omega_r_target, p),
            np.zeros((dim_r, dim_r), dtype=np.int64),
        ):
            R = darboux_basis_from_span(Omega_full, R, p)

        F_r = restrict_operator(F, R, p)
        N_r = restrict_operator(Nstd, R, p)
        Omega_r = omega_matrix(dim_r // 2, p)

        tops = jordan_chain_tops_nilpotent(N_r, int(max_exp), p)
        if not tops and int(max_exp) == 1:
            tops = {1: np.eye(dim_r, dtype=np.int64)}

        extracted = False

        for L in range(int(max_exp), 0, -1):
            X = independent_columns(mod_p(tops.get(L, np.zeros((dim_r, 0), dtype=np.int64)), p), p)
            if X.shape[1] == 0:
                continue

            span_r: Optional[np.ndarray] = None
            mode: Optional[str] = None
            diagnostics: Dict[str, Any] = {}
            fallback_used = False

            try:
                span_r, mode, diagnostics = _extract_block_by_quotient_witt(
                    F_r, N_r, Omega_r, X, int(deg_q), int(L), p
                )
            except Exception as exc:
                diagnostics = {
                    "top_dim": int(X.shape[1]),
                    "quotient_witt_error": f"{type(exc).__name__}: {exc}",
                }
                inv_data["attempts"].append(
                    {
                        "remaining_dim": dim_r,
                        "L": int(L),
                        "found": False,
                        "found_mode": None,
                        "fallback_used": False,
                        **diagnostics,
                    }
                )
                raise RuntimeError(
                    "quotient-form Witt self-sector extraction failed; "
                    f"remaining_dim={dim_r}, L={int(L)}, diagnostics={diagnostics}"
                ) from exc

            inv_data["attempts"].append(
                {
                    "remaining_dim": dim_r,
                    "L": int(L),
                    "found": bool(span_r is not None),
                    "found_mode": mode,
                    "fallback_used": bool(fallback_used),
                    **diagnostics,
                }
            )

            if span_r is None:
                continue

            if span_r.shape[1] % 2 != 0 or not is_nondegenerate(Omega_r, span_r, p):
                continue

            T_blk_r = darboux_basis_from_span(Omega_r, span_r, p)
            T_blk_std = mod_p(R @ T_blk_r, p)
            T_blk_amb = mod_p(T_map @ T_blk_std, p)

            blocks.append(
                AtomicBlock(
                    T_blk=T_blk_amb,
                    half_dim=int(T_blk_amb.shape[1] // 2),
                    sector_key=sector_key,
                    inv=None,
                )
            )

            R_new = symplectic_orthogonal_complement_in_span(Omega_full, T_blk_std, R, p)
            R_new = independent_columns(mod_p(R_new, p), p)

            if R_new.shape[1] == 0:
                R = R_new
            else:
                if R_new.shape[1] % 2 != 0:
                    msg = f"remaining complement odd ({int(R_new.shape[1])})"
                    raise RuntimeError(msg)
                R = darboux_basis_from_span(Omega_full, R_new, p)

            extracted = True
            break

        if not extracted:
            msg = "certified self-sector quotient-Witt extraction stuck"
            tail = inv_data.get("attempts", [])[-3:]
            raise RuntimeError(f"{msg}; last_attempts={tail}")

    if inv_data["status"] == "PENDING":
        inv_data["status"] = "OK"
        inv_data["checks_passed"].append("self_sector_quotient_witt_extracted")
        sector_cost = max((int(b.half_dim) for b in blocks), default=0)
        inv_data["cost_certificate"] = {
            "lower_bound": int(sector_cost),
            "attained": True,
            "complete": True,
            "sector_cost": int(sector_cost),
            "note": (
                "odd-characteristic/nonunipotent self sector certified by quotient-form "
                "Witt decomposition and verified cyclic lifts"
            ),
        }
    else:
        inv_data.setdefault(
            "cost_certificate",
            {
                "lower_bound": None,
                "attained": False,
                "complete": False,
                "sector_cost": max((int(b.half_dim) for b in blocks), default=0),
                "note": "self sector did not complete in certified quotient-Witt mode",
            },
        )

    inv = AtomicInvariant(sector_key=sector_key, sector_type="self", poly_key=poly_key, data=inv_data)
    return blocks, inv
