# sympleq/core/symmetries/atomic_self.py
from __future__ import annotations

import itertools
import numpy as np
from typing import Any, Dict, Tuple, Optional, List

from ..modular_helpers import mod_p, independent_columns, inv_mod_mat, omega_matrix
from .atomic_types import AtomicBlock, AtomicInvariant
from .atomic_linear import (
    is_nondegenerate,
    darboux_basis_from_span,
    restrict_operator,
    symplectic_orthogonal_complement_in_span,
)
from .module_invariants import jordan_chain_tops_nilpotent, cyclic_submodule_basis


def _cyclic_basis(F: np.ndarray, N: np.ndarray, v: np.ndarray, deg_q: int, L: int, p: int) -> np.ndarray:
    """Independent column basis for the cyclic GF(p)[x]-submodule generated by v."""
    C = cyclic_submodule_basis(F, N, v, int(deg_q), int(L), p)
    return independent_columns(mod_p(C, p), p)


def _enumerate_candidate_vectors(
    X: np.ndarray,
    p: int,
    *,
    max_window: int = 4,
    cap: int = 4000,
) -> List[np.ndarray]:
    """Deterministically enumerate a modest set of nonzero vectors in span(X)."""
    X = independent_columns(mod_p(X, p), p)
    t = int(X.shape[1])
    if t == 0:
        return []

    out: List[np.ndarray] = []
    seen: set[Tuple[int, ...]] = set()

    def push(v: np.ndarray) -> None:
        nonlocal out
        v = mod_p(v, p)
        if not np.any(v % p):
            return
        key = tuple(int(x) for x in v.reshape(-1) % p)
        if key in seen:
            return
        seen.add(key)
        out.append(v)

    # Basis vectors first
    for j in range(t):
        push(X[:, j:j + 1])
        if len(out) >= cap:
            return out

    # Small combinations in sliding windows
    wmax = min(int(max_window), t)
    for w in range(2, wmax + 1):
        for start in range(0, t - w + 1):
            Xw = X[:, start:start + w]
            for coeff in itertools.product(range(p), repeat=w):
                if all(c == 0 for c in coeff):
                    continue
                c = np.array(coeff, dtype=np.int64).reshape(w, 1)
                push(Xw @ c)
                if len(out) >= cap:
                    return out

    return out


def atomic_blocks_in_self_sector_nonunipotent(
    F_sec: np.ndarray,
    T_sec: np.ndarray,
    Omega: np.ndarray,
    N: np.ndarray,
    deg_q: int,
    max_exp: int,
    p: int,
    sector_key: Tuple[int, ...],
    poly_key: Tuple[int, ...],
    allow_fallback: bool = True,
) -> tuple[List[AtomicBlock], AtomicInvariant]:
    """
    Certified atomic extraction for self-reciprocal, non-(x±1) sectors.

    IMPORTANT: we do not assume the induced top-space form is a symmetric/alternating bilinear
    GF(p)-form (often false for deg(q)>1 self sectors). We instead do a module-theoretic search:
      - find v in a top space such that C(v) has full cyclic dimension deg(q)*L
      - if C(v) is symplectically nondegenerate, accept it
      - otherwise find w so that C(v) ⊕ C(w) is nondegenerate and has dimension 2*deg(q)*L

    Deterministic + guardrailed; suitable for `mode="certified"`.
    """
    p = int(p)
    F_sec = mod_p(np.asarray(F_sec, dtype=np.int64), p)
    N = mod_p(np.asarray(N, dtype=np.int64), p)
    Omega = mod_p(np.asarray(Omega, dtype=np.int64), p)
    T_sec = mod_p(np.asarray(T_sec, dtype=np.int64), p)

    m = int(F_sec.shape[0])
    if F_sec.shape != (m, m) or N.shape != (m, m) or Omega.shape != (m, m):
        raise ValueError("shape mismatch in self-sector inputs")
    if m % 2 != 0:
        raise ValueError("self-sector dimension must be even")

    inv_data: Dict[str, Any] = {
        "status": "PENDING",
        "deg": int(deg_q),
        "exponent": int(max_exp),
        "note": "",
        "attempts": [],  # per-length diagnostics
        "checks_passed": [],
    }

    # Normalize to standard symplectic form in sector coordinates
    Omega_std = omega_matrix(m // 2, p)
    T_map = T_sec
    if not np.array_equal(mod_p(Omega - Omega_std, p), np.zeros_like(Omega)):
        S = darboux_basis_from_span(Omega, np.eye(m, dtype=np.int64), p)
        Sinv = inv_mod_mat(S, p)
        F = mod_p(Sinv @ F_sec @ S, p)
        Nstd = mod_p(Sinv @ N @ S, p)
        T_map = mod_p(T_sec @ S, p)
        inv_data["checks_passed"].append("darboux_normalized_sector_form")
    else:
        F = F_sec
        Nstd = N

    Omega_full = omega_matrix(m // 2, p)

    # Remaining symplectic basis (columns) in standard sector coords
    R = np.eye(m, dtype=np.int64)

    blocks: List[AtomicBlock] = []

    while R.shape[1] > 0:
        dim_r = int(R.shape[1])
        if dim_r % 2 != 0:
            msg = f"remaining dimension odd ({dim_r})"
            if allow_fallback:
                inv_data["status"] = "DEGRADED"
                inv_data["note"] = msg
                break
            tail = inv_data.get("attempts", [])[-3:]
            raise RuntimeError(f"{msg}; last_attempts={tail}")

        # Ensure R is Darboux
        Omega_r_target = omega_matrix(dim_r // 2, p)
        if not np.array_equal(
            mod_p(R.T @ Omega_full @ R - Omega_r_target, p),
            np.zeros((dim_r, dim_r), dtype=np.int64),
        ):
            R = darboux_basis_from_span(Omega_full, R, p)

        # Restrict operators to remaining subspace (R-coordinates)
        F_r = restrict_operator(F, R, p)
        N_r = restrict_operator(Nstd, R, p)
        Omega_r = omega_matrix(dim_r // 2, p)

        # Jordan tops for N_r
        tops = jordan_chain_tops_nilpotent(N_r, int(max_exp), p)
        if not tops and int(max_exp) == 1:
            tops = {1: np.eye(dim_r, dtype=np.int64)}

        extracted = False

        for L in range(int(max_exp), 0, -1):
            X = independent_columns(mod_p(tops.get(L, np.zeros((dim_r, 0), dtype=np.int64)), p), p)
            if X.shape[1] == 0:
                continue

            target = int(deg_q) * int(L)
            candidates = _enumerate_candidate_vectors(X, p, max_window=4, cap=4000)

            n_tested = 0
            good_cyclic: List[np.ndarray] = []
            span_r: Optional[np.ndarray] = None
            mode = None

            # Try single-generator blocks first
            for v in candidates:
                n_tested += 1
                Cv = _cyclic_basis(F_r, N_r, v, int(deg_q), int(L), p)
                if Cv.shape[1] != target:
                    continue
                if is_nondegenerate(Omega_r, Cv, p):
                    span_r = Cv
                    mode = "single"
                    break
                good_cyclic.append(Cv)

            # If needed, try to find a partner
            if span_r is None and len(good_cyclic) >= 2:
                for a in range(len(good_cyclic)):
                    Cv = good_cyclic[a]
                    for b in range(a + 1, len(good_cyclic)):
                        Cw = good_cyclic[b]
                        both = independent_columns(np.concatenate([Cv, Cw], axis=1), p)
                        if both.shape[1] != 2 * target:
                            continue
                        if is_nondegenerate(Omega_r, both, p):
                            span_r = both
                            mode = "pair"
                            break
                    if span_r is not None:
                        break

            inv_data["attempts"].append(
                {
                    "remaining_dim": dim_r,
                    "L": int(L),
                    "top_dim": int(X.shape[1]),
                    "n_candidates": int(len(candidates)),
                    "n_tested": int(n_tested),
                    "n_full_cyclic": int(len(good_cyclic) + (1 if mode == "single" else 0)),
                    "found": bool(span_r is not None),
                    "found_mode": mode,
                }
            )

            if span_r is None:
                continue

            if span_r.shape[1] % 2 != 0 or not is_nondegenerate(Omega_r, span_r, p):
                continue

            # Build a canonical symplectic basis for this block (in R-coordinates)
            T_blk_r = darboux_basis_from_span(Omega_r, span_r, p)

            # Lift: R-coords -> standard sector coords -> ambient coords
            T_blk_std = mod_p(R @ T_blk_r, p)
            T_blk_amb = mod_p(T_map @ T_blk_std, p)

            blocks.append(
                AtomicBlock(
                    T_blk=T_blk_amb,
                    half_dim=int(T_blk_amb.shape[1] // 2),
                    sector_key=sector_key,
                    inv=None,
                )
            )

            # Update remaining subspace: R <- span(R) ∩ block^⊥
            R_new = symplectic_orthogonal_complement_in_span(Omega_full, T_blk_std, R, p)
            R_new = independent_columns(mod_p(R_new, p), p)

            if R_new.shape[1] == 0:
                R = R_new
            else:
                if R_new.shape[1] % 2 != 0:
                    msg = f"remaining complement odd ({int(R_new.shape[1])})"
                    if allow_fallback:
                        inv_data["status"] = "DEGRADED"
                        inv_data["note"] = msg
                        R = np.zeros((m, 0), dtype=np.int64)
                        break
                    raise RuntimeError(msg)
                R = darboux_basis_from_span(Omega_full, R_new, p)

            extracted = True
            break

        if inv_data.get("status") == "DEGRADED":
            break

        if not extracted:
            msg = "certified self-sector extraction stuck"
            if allow_fallback:
                inv_data["status"] = "DEGRADED"
                if not inv_data["note"]:
                    inv_data["note"] = msg
                break
            tail = inv_data.get("attempts", [])[-3:]
            raise RuntimeError(f"{msg}; last_attempts={tail}")

    if inv_data["status"] == "PENDING":
        inv_data["status"] = "OK"

    inv = AtomicInvariant(sector_key=sector_key, sector_type="self", poly_key=poly_key, data=inv_data)
    return blocks, inv
