name: Enhancement request
description: Suggest an improvement or refinement to existing features
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        ## Enhancement Request

        Thank you for suggesting an enhancement to improve the project!
  - type: textarea
    id: description
    attributes:
      label: Describe the enhancement
      description: A clear and concise description of the improvement you are proposing.
      placeholder: I suggest improving...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why is this enhancement important? What problem does it solve or what value does it add?
      placeholder: This would help because...
    validations:
      required: false
  - type: textarea
    id: current_behavior
    attributes:
      label: Current behavior
      description: What is the current behavior or limitation?
      placeholder: Currently...
    validations:
      required: false
  - type: textarea
    id: proposed_behavior
    attributes:
      label: Proposed behavior
      description: What would you like to see changed or improved?
      placeholder: I would like to see...
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, examples, or screenshots about the enhancement here.
      placeholder: Any other details...
    validations:
