# sympleq/core/symmetries/atomic_self.py
from __future__ import annotations

import numpy as np
from typing import Any, Dict, List, Tuple, Optional

from .modular_helpers import mod_p, rank_mod
from .atomic_types import AtomicBlock, AtomicInvariant
from .atomic_linear import (
    independent_columns,
    is_nondegenerate,
    darboux_basis_from_span,
)


def _pair_value(v: np.ndarray, w: np.ndarray, Omega: np.ndarray, N: np.ndarray, L: int, p: int) -> int:
    """Chain-level induced pairing: <v, N^{L-1} w>."""
    if L <= 0:
        raise ValueError("L must be >= 1")
    Nr = np.eye(N.shape[0], dtype=np.int64) if (L - 1) == 0 else mat_pow_mod(N, L - 1, p)
    val = mod_p(v.T @ Omega @ (Nr @ w), p)
    return int(val.reshape(()))


def mat_pow_mod(A: np.ndarray, e: int, p: int) -> np.ndarray:
    """Fast exponentiation mod p."""
    if e < 0:
        raise ValueError("Negative exponent not supported in mat_pow_mod.")
    n = A.shape[0]
    R = np.eye(n, dtype=np.int64)
    B = mod_p(A, p).copy()
    k = e
    while k > 0:
        if k & 1:
            R = mod_p(R @ B, p)
        B = mod_p(B @ B, p)
        k >>= 1
    return R


def symplectic_orthogonal_complement_in_span(
    Omega: np.ndarray, T_block: np.ndarray, space_basis: np.ndarray, p: int
) -> np.ndarray:
    """
    Given:
      - space_basis: columns span current working subspace S (subset of sector coords)
      - T_block: columns span extracted symplectic subspace W (subset of S)
    Return columns spanning S ∩ W^⊥ (symplectic orthogonal complement inside S).
    """
    if space_basis.shape[1] == 0:
        return space_basis

    # Solve for coefficients c such that (space_basis c) is orthogonal to W:
    # < space_basis c, T_block > = 0  =>  c^T (space_basis^T Omega T_block) = 0.
    M = mod_p(space_basis.T @ Omega @ T_block, p)  # (dimS x dimW)
    # Nullspace of M^T corresponds to orthogonal vectors in coefficient space
    # i.e. M^T c = 0.
    MT = mod_p(M.T, p)
    ker = nullspace_basis_mod(MT, p)  # columns in coefficient space
    if ker.shape[1] == 0:
        return np.zeros((space_basis.shape[0], 0), dtype=np.int64)

    rem = mod_p(space_basis @ ker, p)
    rem = independent_columns(rem, p)
    return rem


def nullspace_basis_mod(A: np.ndarray, p: int) -> np.ndarray:
    """Return a basis (columns) for the nullspace of A over GF(p)."""
    A = mod_p(A, p)
    m, n = A.shape
    if m == 0:
        return np.eye(n, dtype=np.int64)

    # Row-reduce A to RREF and track pivots
    R, pivots = rref_mod(A, p)
    pivots = list(pivots)
    pivot_set = set(pivots)
    free = [j for j in range(n) if j not in pivot_set]
    if not free:
        return np.zeros((n, 0), dtype=np.int64)

    # Build nullspace vectors for each free var
    basis = []
    for f in free:
        x = np.zeros((n, 1), dtype=np.int64)
        x[f, 0] = 1
        # For each pivot row i, pivot col = pivots[i], solve x[piv] = -R[i,f]
        for i, pc in enumerate(pivots):
            x[pc, 0] = (-R[i, f]) % p
        basis.append(x)

    return mod_p(np.concatenate(basis, axis=1), p)


def rref_mod(A: np.ndarray, p: int) -> Tuple[np.ndarray, List[int]]:
    """Reduced row echelon form over GF(p); returns (RREF, pivot_cols)."""
    A = mod_p(A, p).copy()
    m, n = A.shape
    pivots: List[int] = []
    r = 0
    for c in range(n):
        if r >= m:
            break
        # find pivot row
        piv = None
        for rr in range(r, m):
            if A[rr, c] % p != 0:
                piv = rr
                break
        if piv is None:
            continue
        # swap
        if piv != r:
            A[[r, piv]] = A[[piv, r]]
        # normalize pivot row
        inv = pow(int(A[r, c]), p - 2, p) if p != 2 else 1
        A[r, :] = (A[r, :] * inv) % p
        # eliminate other rows
        for rr in range(m):
            if rr == r:
                continue
            if A[rr, c] % p != 0:
                factor = A[rr, c] % p
                A[rr, :] = (A[rr, :] - factor * A[r, :]) % p
        pivots.append(c)
        r += 1
    return A, pivots


def cyclic_submodule_basis(F_sec: np.ndarray, N: np.ndarray, v_top: np.ndarray, deg_q: int, L: int, p: int) -> np.ndarray:
    """
    Build a basis for the cyclic F-module generated by v_top, truncated to the expected
    size deg_q * L. Uses the restricted coordinates on the current sector.
    """
    # We build v, vF, vF^2, ..., but we can exploit primary structure: size target = deg_q*L.
    target = deg_q * L
    rows = []
    v = mod_p(v_top.reshape(-1, 1), p)
    cur = v
    for _ in range(target * 2 + 4):  # overshoot guard; independent_columns will trim
        rows.append(cur)
        cur = mod_p(F_sec.T @ cur, p)  # NOTE: v are column vectors here; row convention -> right-mult means col transforms by F^T
        if len(rows) >= target:
            # not safe to break early; still allow more to resolve dependence, but keep a cap above
            pass
        if len(rows) > target * 2 + 3:
            break
    M = mod_p(np.concatenate(rows, axis=1), p)
    M = independent_columns(M, p)
    # Truncate if too large (shouldn't happen for correct primary/truncation)
    if M.shape[1] > target:
        M = M[:, :target]
    return M


def jordan_chain_tops_nilpotent_in_span(N: np.ndarray, space_basis: np.ndarray, max_exp: int, p: int) -> Dict[int, np.ndarray]:
    """
    Return top representatives at each length L, within the current working span S=span(space_basis),
    for the nilpotent N on this restricted space.

    Output dict: L -> matrix whose columns span a complement for
        T_L := K_L / (K_{L-1} + N K_{L+1})
    represented as actual vectors in S.

    NOTE: This is a deterministic construction used by the atomic routines.
    """
    # Work in coordinate space of S: represent N_S = (space_basis)^+ N (space_basis)
    # but we can stay in ambient by repeated kernels inside span.

    # Build K_j = { v in S : v N^j = 0 }.
    # With column-vector convention for computations: condition is N^T^j v = 0 in col form
    # since row v satisfies v N^j = 0 <=> (N^T)^j v^T = 0.
    tops: Dict[int, np.ndarray] = {}
    if space_basis.shape[1] == 0:
        return tops

    # Precompute (N^T)^j
    Nt = mod_p(N.T, p)
    Nt_pows = [np.eye(N.shape[0], dtype=np.int64)]
    for j in range(1, max_exp + 2):
        Nt_pows.append(mod_p(Nt_pows[-1] @ Nt, p))

    # Helper: kernel in S of linear map A (ambient): {x in S : A x = 0}
    def ker_in_span(A: np.ndarray) -> np.ndarray:
        AS = mod_p(A @ space_basis, p)
        coeff = nullspace_basis_mod(AS, p)  # coefficients c with AS c = 0
        return mod_p(space_basis @ coeff, p)

    K = [np.zeros((N.shape[0], 0), dtype=np.int64)]  # K0
    for j in range(1, max_exp + 2):
        Kj = ker_in_span(Nt_pows[j])
        Kj = independent_columns(Kj, p)
        K.append(Kj)

    # Build T_L complements: K_L / (K_{L-1} + N K_{L+1})
    for L in range(1, max_exp + 1):
        K_L = K[L]
        if K_L.shape[1] == 0:
            continue
        sum_space = K[L - 1]
        NKLp1 = mod_p(Nt @ K[L + 1], p)  # in col form, image under Nt corresponds to row*N
        denom = sum_space
        if NKLp1.shape[1] > 0:
            denom = np.concatenate([denom, NKLp1], axis=1) if denom.shape[1] > 0 else NKLp1
        denom = independent_columns(denom, p) if denom.shape[1] > 0 else denom

        # Complement of denom inside K_L: find columns in K_L not in span(denom)
        if denom.shape[1] == 0:
            tops[L] = K_L
        else:
            # Solve K_L = denom * X + comp * Y; get comp by extending denom to basis of K_L
            comp = complement_columns_mod(denom, K_L, p)
            if comp.shape[1] > 0:
                tops[L] = comp

    return tops


def complement_columns_mod(A: np.ndarray, B: np.ndarray, p: int) -> np.ndarray:
    """
    Given A (n x a) and B (n x b) with span(A) subset span(B),
    return columns of B that complement A to a basis of span(B).
    """
    if B.shape[1] == 0:
        return B
    if A.shape[1] == 0:
        return independent_columns(B, p)

    # Build [A | B] and find a basis; then pick those basis columns coming from B but not from A.
    AB = mod_p(np.concatenate([A, B], axis=1), p)
    R, piv = rref_mod(AB.T, p)  # row-reduce transposed to find independent columns in AB (hacky but works)
    # Actually rref_mod above is for rows; better: do rref on AB and get pivot cols.
    # We'll do a simple pivot selection using rank increments.
    piv_cols = []
    cur = np.zeros((AB.shape[0], 0), dtype=np.int64)
    cur_rank = 0
    for j in range(AB.shape[1]):
        cand = np.concatenate([cur, AB[:, j:j + 1]], axis=1)
        r = rank_mod(cand, p)
        if r > cur_rank:
            piv_cols.append(j)
            cur = cand
            cur_rank = r

    # From pivots, return those that are from B-part and not already in A-part
    comp_cols = [j - A.shape[1] for j in piv_cols if j >= A.shape[1]]
    if not comp_cols:
        return np.zeros((B.shape[0], 0), dtype=np.int64)
    return mod_p(B[:, comp_cols], p)


def _full_top_space_basis_in_span(N: np.ndarray, space_basis: np.ndarray, L: int, p: int) -> np.ndarray:
    """
    Return a basis (columns) for K_L within current span S (space_basis).
    This is used to solve for a top partner w satisfying <v, N^{L-1} w> = 1.
    """
    Nt = mod_p(N.T, p)
    NtL = mat_pow_mod(Nt, L, p)

    AS = mod_p(NtL @ space_basis, p)
    coeff = nullspace_basis_mod(AS, p)
    K_L = mod_p(space_basis @ coeff, p)
    K_L = independent_columns(K_L, p)
    return K_L


def _select_module_generators_from_top_space(
    F_sec: np.ndarray, N: np.ndarray, A_raw: np.ndarray, deg_q: int, L: int, p: int
) -> np.ndarray:
    """
    Convert a basis for top quotient reps at length L into a reduced set of module generators.
    Acceptance test: cyclic_submodule_basis has expected dimension deg_q * L.
    """
    if A_raw.shape[1] == 0:
        return A_raw

    gens = []
    target = deg_q * L
    for j in range(A_raw.shape[1]):
        v = A_raw[:, j:j + 1]
        Cv = cyclic_submodule_basis(F_sec, N, v, deg_q, L, p)
        Cv = independent_columns(Cv, p)
        if Cv.shape[1] == target:
            gens.append(v)

    if not gens:
        return np.zeros((A_raw.shape[0], 0), dtype=np.int64)

    G = mod_p(np.concatenate(gens, axis=1), p)
    G = independent_columns(G, p)
    return G


def _find_partner_in_top_span(
    v_top: np.ndarray, A_top: np.ndarray, Omega: np.ndarray, N: np.ndarray, L: int, p: int
) -> np.ndarray:
    """
    Find w in span(A_top) such that <v, N^{L-1} w> = 1.
    Deterministic and solver-free: since this is a single equation, we just pick the
    first top-basis direction with nonzero pairing and scale it.
    """
    if A_top.shape[1] == 0:
        raise RuntimeError("Top space is empty; cannot find hyperbolic partner.")

    Nr = np.eye(N.shape[0], dtype=np.int64) if (L - 1) == 0 else mat_pow_mod(N, L - 1, p)

    # row[j] = <v, N^{L-1} A_top[:,j]>
    row = mod_p(v_top.T @ Omega @ (Nr @ A_top), p).reshape(-1)  # shape (dimTop,)

    # Deterministic: choose first nonzero coordinate
    j = None
    for idx in range(row.size):
        if int(row[idx] % p) != 0:
            j = idx
            break
    if j is None:
        raise RuntimeError("No partner exists in span(A_top) with nonzero induced pairing.")

    w = mod_p(A_top[:, j:j + 1], p)
    a = int(row[j] % p)

    # scale so pairing becomes 1
    if p == 2:
        # only possible nonzero is 1, so already normalized
        return w
    inva = pow(a, p - 2, p)
    return mod_p(w * inva, p)


def _cyclic_module_basis_checked(
    F_sec: np.ndarray,
    N: np.ndarray,
    v_top: np.ndarray,
    deg_q: int,
    L: int,
    p: int,
) -> np.ndarray:
    """Return a cyclic module basis and enforce the expected dimension deg_q*L.

    This is an Upgrade-B guardrail: in self sectors, choosing a partner from the
    *top span* (or even from a top quotient basis) can accidentally pick a vector
    that does not generate a full indecomposable summand (it can collapse to a
    shorter chain, or share an already-accounted-for module). We therefore only
    accept v if its cyclic span has the expected dimension.
    """
    target = int(deg_q) * int(L)
    Cv = cyclic_submodule_basis(F_sec, N, v_top, deg_q, int(L), p)
    Cv = independent_columns(mod_p(Cv, p), p)
    if Cv.shape[1] != target:
        raise RuntimeError(
            f"Top vector does not generate a full module: got dim={Cv.shape[1]}, expected {target}."
        )
    return Cv


def _try_hyperbolic_pair_from_generators(
    F_sec: np.ndarray,
    N: np.ndarray,
    v_top: np.ndarray,
    Cv: np.ndarray,
    other_gens: np.ndarray,
    Omega: np.ndarray,
    deg_q: int,
    L: int,
    p: int,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Find a hyperbolic partner w among *verified* module generators.

    Returns (w_top, Cw, span) with:
      - Cw has dim = deg_q*L
      - span = span(Cv, Cw) has dim = 2*deg_q*L and is symplectically nondegenerate
    """
    exp_single = int(deg_q) * int(L)
    exp_pair = 2 * exp_single

    if other_gens.shape[1] == 0:
        raise RuntimeError("No other generator available to pair with.")

    for j in range(other_gens.shape[1]):
        cand = other_gens[:, j:j + 1]
        a = _pair_value(v_top, cand, Omega, N, int(L), p) % p
        if a == 0:
            continue
        inva = pow(int(a), p - 2, p) if p != 2 else 1
        cand = mod_p(cand * inva, p)

        # Enforce full module on the partner.
        try:
            Ccand = _cyclic_module_basis_checked(F_sec, N, cand, deg_q, int(L), p)
        except RuntimeError:
            continue

        span = independent_columns(np.concatenate([Cv, Ccand], axis=1), p)
        if span.shape[1] != exp_pair:
            continue
        if span.shape[1] % 2 != 0:
            continue
        if not is_nondegenerate(Omega, span, p):
            continue

        return cand, Ccand, span

    raise RuntimeError("Failed to find a certified hyperbolic partner among generators.")


# -------------------------
# Main entry: self sector decomposition (non-unipotent)
# -------------------------


def atomic_blocks_in_self_sector_nonunipotent(
    F_sec: np.ndarray,
    T_sec: np.ndarray,
    Omega: np.ndarray,
    N: np.ndarray,
    deg_q: int,
    max_exp: int,
    key: Tuple[int, int],
    p: int,
    *,
    allow_fallback: bool = True,
) -> Tuple[List[AtomicBlock], AtomicInvariant]:
    """
    Decompose a self-reciprocal symplectic sector W_phi=V_phi (phi=phi^*), excluding the
    p=2 unipotent special case handled elsewhere.

    Returns:
      - list of AtomicBlock with bases in ambient coordinates (T_sec maps sector->ambient)
      - AtomicInvariant object describing the sector decomposition status
    """
    # Robustness: keep original exponent for reporting (even if we shrink exp_work later).
    max_exp_orig = int(max_exp)

    Ω = mod_p(Omega, p)

    m = F_sec.shape[0] // 2
    assert F_sec.shape == (2 * m, 2 * m)

    # Precompute top multiplicities / top forms (diagnostics)
    top_multiplicities: Dict[int, int] = {}
    top_form: Dict[int, Any] = {}

    # Working max length (can shrink if we can't safely extract at long lengths)
    exp_work = int(max_exp)

    blocks: List[AtomicBlock] = []
    blocks_meta: List[Dict[str, Any]] = []

    # keep accepted block bases in sector coordinates for span sanity-check
    built_cols_sec: List[np.ndarray] = []

    space_basis = np.eye(2 * m, dtype=np.int64)

    extraction_error: Exception | None = None
    try:
        while space_basis.shape[1] > 0:
            # tops in current space (use exp_work, which may shrink deterministically)
            if exp_work <= 0:
                break
            tops = jordan_chain_tops_nilpotent_in_span(N, space_basis, exp_work, p)
            if not tops:
                break

            L = max(tops.keys())

            A_raw = independent_columns(mod_p(tops[L], p), p)

            # Reduced set: one per indecomposable q^L block (module generators)
            A = _select_module_generators_from_top_space(F_sec, N, A_raw, deg_q, int(L), p)

            if A.shape[1] == 0:
                # nothing usable at this L; deterministically drop this length
                exp_work = int(L) - 1
                continue

            # -------------------------
            # Upgrade B extraction at fixed length L:
            #   - only accept v/w that generate *full* cyclic modules (dim = deg_q*L)
            #   - if hyperbolic pairing is needed, prefer partners among verified generators
            #     (this is the robust, basis-independent version of "pair in the top space")
            # -------------------------
            exp_single = int(deg_q) * int(L)
            exp_pair = 2 * exp_single

            made_block = False
            # Delay construction of the full top-space basis unless we need a fallback.
            A_top: np.ndarray | None = None

            for i in range(A.shape[1]):
                v_top = A[:, i:i + 1]

                # Candidate 1: self-dual cyclic module
                try:
                    Cv = _cyclic_module_basis_checked(F_sec, N, v_top, deg_q, int(L), p)
                except RuntimeError:
                    # Despite passing the generator test, v may still collapse numerically;
                    # treat as unusable and try next.
                    continue

                bvv = _pair_value(v_top, v_top, Ω, N, int(L), p)

                if (Cv.shape[1] % 2 == 0) and is_nondegenerate(Ω, Cv, p):
                    T_blk = darboux_basis_from_span(Ω, Cv, p)  # SECTOR COORDS
                    built_cols_sec.append(T_blk)

                    rem = symplectic_orthogonal_complement_in_span(Ω, T_blk, space_basis, p)

                    T_blk_amb = mod_p(T_sec @ T_blk, p)
                    blocks.append(
                        AtomicBlock(
                            T_blk=T_blk_amb,
                            half_dim=int(T_blk_amb.shape[1] // 2),
                            sector_key=key,
                            inv=None,
                        )
                    )
                    blocks_meta.append(
                        {"type": "self", "L": int(L), "half_dim": int(T_blk_amb.shape[1] // 2), "bvv": int(bvv)}
                    )
                    space_basis = rem
                    made_block = True
                    break

                # Candidate 2: hyperbolic pairing with a *verified* generator partner
                other_gens = (
                    np.concatenate([A[:, :i], A[:, i + 1:]], axis=1)
                    if A.shape[1] > 1
                    else np.zeros((A.shape[0], 0), dtype=np.int64)
                )

                try:
                    w_top, Cw, span = _try_hyperbolic_pair_from_generators(
                        F_sec, N, v_top, Cv, other_gens, Ω, deg_q, int(L), p
                    )
                except RuntimeError:
                    # Fallback: allow *any* partner in the full top space, but still
                    # enforce the full-module and full-block dimension checks.
                    if A_top is None:
                        A_top = _full_top_space_basis_in_span(N, space_basis, int(L), p)
                    try:
                        w_top = _find_partner_in_top_span(v_top, A_top, Ω, N, int(L), p)
                        Cw = _cyclic_module_basis_checked(F_sec, N, w_top, deg_q, int(L), p)
                    except Exception:
                        continue

                    span = independent_columns(np.concatenate([Cv, Cw], axis=1), p)
                    if span.shape[1] != exp_pair:
                        continue
                    if span.shape[1] % 2 != 0 or not is_nondegenerate(Ω, span, p):
                        continue

                # At this point we have a certified hyperbolic block.
                if span.shape[1] != exp_pair:
                    continue

                T_blk = darboux_basis_from_span(Ω, span, p)  # SECTOR COORDS
                built_cols_sec.append(T_blk)

                rem = symplectic_orthogonal_complement_in_span(Ω, T_blk, space_basis, p)

                T_blk_amb = mod_p(T_sec @ T_blk, p)
                blocks.append(
                    AtomicBlock(
                        T_blk=T_blk_amb,
                        half_dim=int(T_blk_amb.shape[1] // 2),
                        sector_key=key,
                        inv=None,
                    )
                )
                blocks_meta.append(
                    {"type": "hyperbolic", "L": int(L), "half_dim": int(T_blk_amb.shape[1] // 2), "bvv": int(bvv)}
                )
                space_basis = rem
                made_block = True
                break

            if not made_block:
                # No extractable block at this length: deterministically drop this length.
                exp_work = int(L) - 1
                continue

    except Exception as e:
        extraction_error = e

    # If extraction failed in p=2, optionally degrade to a single sector-sized block.
    if extraction_error is not None and p == 2 and allow_fallback:
        blocks = [AtomicBlock(T_blk=mod_p(T_sec, p), half_dim=m, sector_key=key, inv=None)]
        blocks_meta = [{
            "type": "fallback_sector",
            "half_dim": int(m),
            "note": f"{type(extraction_error).__name__}: {extraction_error}",
        }]
        built_cols_sec = []  # skip span-check in degraded mode

    # Span sanity-check (only if we did not degrade)
    if extraction_error is None:
        dim_sector = 2 * m
        if built_cols_sec:
            all_cols_sec = np.concatenate(built_cols_sec, axis=1)
            dim_blocks = rank_mod(all_cols_sec, p)
        else:
            dim_blocks = 0

        if dim_blocks != dim_sector:
            raise RuntimeError(
                f"Self sector: blocks do not span sector "
                f"(dim_blocks={dim_blocks}, dim_sector={dim_sector}). "
                f"key={key}, deg={deg_q}, exp={max_exp_orig}"
            )

    # Status / invariant payload
    if extraction_error is not None:
        status = "DEGRADED_p2" if p == 2 else "ERROR"
    else:
        # If we got here, extraction succeeded. We can certify p=2 too *if* the
        # spanning / consistency checks passed (they did, otherwise we'd have raised).
        status = "OK"

    inv_data: Dict[str, Any] = {
        "status": status,
        "deg": int(deg_q),
        "exponent": int(max_exp_orig),          # report the true primary exponent
        "exp_work_final": int(exp_work),        # optional: helps debugging
        "top_multiplicities": top_multiplicities,
        "top_form": top_form,
        "blocks": blocks_meta,
    }
    if extraction_error is not None:
        inv_data["note"] = f"{type(extraction_error).__name__}: {extraction_error}"

    inv = AtomicInvariant(sector_key=key, sector_type="self", poly_key=key, data=inv_data)
    blocks = [AtomicBlock(b.T_blk, b.half_dim, key, inv) for b in blocks]
    return blocks, inv
